FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build

WORKDIR /src

COPY . .

RUN dotnet restore "PROG7311POEAPI.csproj"

RUN dotnet publish "PROG7311POEAPI.csproj" \
-c Release \
-o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0

WORKDIR /app

COPY --from=build /app/publish .

EXPOSE 8080

ENTRYPOINT ["dotnet","PROG7311POEAPI.dll"]