FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY . .

RUN dotnet restore "Prog7311PoeTwo.csproj"

RUN dotnet publish "Prog7311PoeTwo.csproj" \
-c Release \
-o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0

WORKDIR /app

COPY --from=build /app/publish .

EXPOSE 80

ENTRYPOINT ["dotnet","Prog7311PoeTwo.dll"]